### ISSUE TITLE
positional argument error

### ISSUE THREAD

**Issue by mward29** [mwisslead/vfp2py#3]
I came across the project and have a similar need. Attempting to run it against a .pjx I get the following:

Traceback (most recent call last):
  File "/usr/local/bin/vfp2py", line 11, in <module>
    load_entry_point('vfp2py==0.1.0', 'console_scripts', 'vfp2py')()
  File "/usr/local/lib/python3.7/site-packages/vfp2py-0.1.0-py3.7.egg/vfp2py/__main__.py", line 28, in main
    vfp2py.convert_file(args.infile, args.outpath, encoding=args.encoding)
  File "/usr/local/lib/python3.7/site-packages/vfp2py-0.1.0-py3.7.egg/vfp2py/vfp2py.py", line 503, in convert_file
    convert_project(infile, outfile, encoding)
TypeError: convert_project() takes 2 positional arguments but 3 were given

**Comment by mwisslead** [comment]
Must have missed that in a recent change. Pushed a fix up.

**Comment by mward29** [comment]
Thanks. closing
