### ISSUE TITLE
Syntax: SET UDFPARMS to VALUE 

### ISSUE THREAD

**Issue by mward29** [mwisslead/vfp2py#4]
I'm not sure but this just feels like an issue because I'm on mac or a bad package version.
Thoughts?

python 3.7
OSX

pip3 list
Package                Version
---------------------- -------
aenum                  2.2.3
antlr4-python3-runtime 4.8
autopep8               1.5.3
dbf                    0.98.3
isort                  4.3.21
pip                    20.1.1
pycodestyle            2.6.0
pyodbc                 4.0.30
python-dateutil        2.8.1
setuptools             49.2.0
six                    1.15.0
toml                   0.10.1
wheel                  0.34.2

`vfp2py file.prg test`

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/vfp2py-0.1.0-py3.7.egg/vfp2py/vfp2py.py", line 465, in run_parser
    return getattr(parser, parser_start)()
  File "/usr/local/lib/python3.7/site-packages/vfp2py-0.1.0-py3.7.egg/vfp2py/VisualFoxpro9Parser.py", line 2371, in prg
    self.match(VisualFoxpro9Parser.EOF)
  File "/usr/local/lib/python3.7/site-packages/antlr4_python3_runtime-4.8-py3.7.egg/antlr4/Parser.py", line 118, in match
    t = self._errHandler.recoverInline(self)
  File "/usr/local/lib/python3.7/site-packages/antlr4_python3_runtime-4.8-py3.7.egg/antlr4/error/ErrorStrategy.py", line 692, in recoverInline
    self.recover(recognizer, InputMismatchException(recognizer))
  File "/usr/local/lib/python3.7/site-packages/antlr4_python3_runtime-4.8-py3.7.egg/antlr4/error/ErrorStrategy.py", line 686, in recover
    raise ParseCancellationException(e)
antlr4.error.Errors.ParseCancellationException: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/vfp2py", line 11, in <module>
    load_entry_point('vfp2py==0.1.0', 'console_scripts', 'vfp2py')()
  File "/usr/local/lib/python3.7/site-packages/vfp2py-0.1.0-py3.7.egg/vfp2py/__main__.py", line 28, in main
    vfp2py.convert_file(args.infile, args.outpath, encoding=args.encoding)
  File "/usr/local/lib/python3.7/site-packages/vfp2py-0.1.0-py3.7.egg/vfp2py/vfp2py.py", line 536, in convert_file
    output = prg2py_after_preproc(data, 'prg', os.path.splitext(os.path.basename(infile))[0])
  File "/usr/local/lib/python3.7/site-packages/vfp2py-0.1.0-py3.7.egg/vfp2py/vfp2py.py", line 479, in prg2py_after_preproc
    tree = run_parser(stream, parser, parser_start)
  File "/usr/local/lib/python3.7/site-packages/vfp2py-0.1.0-py3.7.egg/vfp2py/vfp2py.py", line 472, in run_parser
    return getattr(parser, parser_start)()
  File "/usr/local/lib/python3.7/site-packages/vfp2py-0.1.0-py3.7.egg/vfp2py/VisualFoxpro9Parser.py", line 2367, in prg
    self._errHandler.sync(self)
  File "/usr/local/lib/python3.7/site-packages/antlr4_python3_runtime-4.8-py3.7.egg/antlr4/error/ErrorStrategy.py", line 223, in sync
    self.reportUnwantedToken(recognizer)
  File "/usr/local/lib/python3.7/site-packages/antlr4_python3_runtime-4.8-py3.7.egg/antlr4/error/ErrorStrategy.py", line 307, in reportUnwantedToken
    recognizer.notifyErrorListeners(msg, t, None)
  File "/usr/local/lib/python3.7/site-packages/antlr4_python3_runtime-4.8-py3.7.egg/antlr4/Parser.py", line 314, in notifyErrorListeners
    listener.syntaxError(self, offendingToken, line, column, msg, e)
  File "/usr/local/lib/python3.7/site-packages/antlr4_python3_runtime-4.8-py3.7.egg/antlr4/error/ErrorListener.py", line 60, in syntaxError
    delegate.syntaxError(recognizer, offendingSymbol, line, column, msg, e)
  File "/usr/local/lib/python3.7/site-packages/vfp2py-0.1.0-py3.7.egg/vfp2py/vfp2py.py", line 458, in syntaxError
    raise Exception('Syntax Error on line {}: {}'.format(line, linetxt))
Exception: Syntax Error on line 17: SET UDFPARMS to VALUE

**Comment by mwisslead** [comment]
Syntax error because I don't have SET UDFPARMS command in the grammar. I'll add something for it. Lots of the more obscure commands are probably still missing also

**Comment by mward29** [comment]
complete.
